#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullTiltSoccerRS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FullTiltSoccerDB")]
	public partial class FullTiltSoccerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCamp(Camp instance);
    partial void UpdateCamp(Camp instance);
    partial void DeleteCamp(Camp instance);
    partial void InsertCoachesCorner(CoachesCorner instance);
    partial void UpdateCoachesCorner(CoachesCorner instance);
    partial void DeleteCoachesCorner(CoachesCorner instance);
    partial void InsertRegion(Region instance);
    partial void UpdateRegion(Region instance);
    partial void DeleteRegion(Region instance);
    partial void InsertTournament(Tournament instance);
    partial void UpdateTournament(Tournament instance);
    partial void DeleteTournament(Tournament instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertCountry(Country instance);
    partial void UpdateCountry(Country instance);
    partial void DeleteCountry(Country instance);
    #endregion
		
		public FullTiltSoccerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FullTiltSoccerDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FullTiltSoccerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FullTiltSoccerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FullTiltSoccerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FullTiltSoccerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Camp> Camps
		{
			get
			{
				return this.GetTable<Camp>();
			}
		}
		
		public System.Data.Linq.Table<CmsData> CmsDatas
		{
			get
			{
				return this.GetTable<CmsData>();
			}
		}
		
		public System.Data.Linq.Table<CoachesCorner> CoachesCorners
		{
			get
			{
				return this.GetTable<CoachesCorner>();
			}
		}
		
		public System.Data.Linq.Table<Region> Regions
		{
			get
			{
				return this.GetTable<Region>();
			}
		}
		
		public System.Data.Linq.Table<Tournament> Tournaments
		{
			get
			{
				return this.GetTable<Tournament>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Country> Countries
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllActiveCoachesCornerListings")]
		public ISingleResult<GetAllActiveCoachesCornerListingsResult> GetAllActiveCoachesCornerListings([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> currentDay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), currentDay);
			return ((ISingleResult<GetAllActiveCoachesCornerListingsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCoachesCornerRegionListing")]
		public ISingleResult<GetCoachesCornerRegionListingResult> GetCoachesCornerRegionListing([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> currentDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> countryID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> regionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), currentDate, countryID, regionID);
			return ((ISingleResult<GetCoachesCornerRegionListingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllActiveTournaments")]
		public ISingleResult<GetAllActiveTournamentsResult> GetAllActiveTournaments([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> currentDay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), currentDay);
			return ((ISingleResult<GetAllActiveTournamentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllCoachesCornerListings")]
		public ISingleResult<GetAllCoachesCornerListingsResult> GetAllCoachesCornerListings()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllCoachesCornerListingsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllTournaments")]
		public ISingleResult<GetAllTournamentsResult> GetAllTournaments()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllTournamentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllTournamentsByUser")]
		public ISingleResult<GetAllTournamentsByUserResult> GetAllTournamentsByUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((ISingleResult<GetAllTournamentsByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCMSDataById")]
		public ISingleResult<CmsData> GetCMSDataById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMSID", DbType="VarChar(50)")] string cMSID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cMSID);
			return ((ISingleResult<CmsData>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCoachesCornerRegionListingByAge")]
		public ISingleResult<GetCoachesCornerRegionListingByAgeResult> GetCoachesCornerRegionListingByAge([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> currentDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> countryID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> regionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> age)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), currentDate, countryID, regionID, age);
			return ((ISingleResult<GetCoachesCornerRegionListingByAgeResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Camps")]
	public partial class Camp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CampsID;
		
		private System.DateTime _ExpirationDate;
		
		private string _Source;
		
		private string _URL;
		
		private string _ImageSize;
		
		private int _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCampsIDChanging(int value);
    partial void OnCampsIDChanged();
    partial void OnExpirationDateChanging(System.DateTime value);
    partial void OnExpirationDateChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnImageSizeChanging(string value);
    partial void OnImageSizeChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public Camp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CampsID
		{
			get
			{
				return this._CampsID;
			}
			set
			{
				if ((this._CampsID != value))
				{
					this.OnCampsIDChanging(value);
					this.SendPropertyChanging();
					this._CampsID = value;
					this.SendPropertyChanged("CampsID");
					this.OnCampsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="Date NOT NULL")]
		public System.DateTime ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageSize", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ImageSize
		{
			get
			{
				return this._ImageSize;
			}
			set
			{
				if ((this._ImageSize != value))
				{
					this.OnImageSizeChanging(value);
					this.SendPropertyChanging();
					this._ImageSize = value;
					this.SendPropertyChanged("ImageSize");
					this.OnImageSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CmsData")]
	public partial class CmsData
	{
		
		private string _CmdID;
		
		private string _Text;
		
		public CmsData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CmdID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CmdID
		{
			get
			{
				return this._CmdID;
			}
			set
			{
				if ((this._CmdID != value))
				{
					this._CmdID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CoachesCorner")]
	public partial class CoachesCorner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AgeGroup;
		
		private string _Gender;
		
		private string _TeamName;
		
		private string _ClubName;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DatePosted;
		
		private string _ContactName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _Website;
		
		private System.Nullable<System.DateTime> _DateRemove;
		
		private string _City;
		
		private System.Nullable<int> _RegionID;
		
		private int _CoachesCornerID;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgeGroupChanging(string value);
    partial void OnAgeGroupChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnTeamNameChanging(string value);
    partial void OnTeamNameChanged();
    partial void OnClubNameChanging(string value);
    partial void OnClubNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDatePostedChanging(System.Nullable<System.DateTime> value);
    partial void OnDatePostedChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnDateRemoveChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRemoveChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnRegionIDChanging(System.Nullable<int> value);
    partial void OnRegionIDChanged();
    partial void OnCoachesCornerIDChanging(int value);
    partial void OnCoachesCornerIDChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public CoachesCorner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(MAX)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this.OnAgeGroupChanging(value);
					this.SendPropertyChanging();
					this._AgeGroup = value;
					this.SendPropertyChanged("AgeGroup");
					this.OnAgeGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="VarChar(MAX)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this.OnTeamNameChanging(value);
					this.SendPropertyChanging();
					this._TeamName = value;
					this.SendPropertyChanged("TeamName");
					this.OnTeamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="VarChar(MAX)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this.OnClubNameChanging(value);
					this.SendPropertyChanging();
					this._ClubName = value;
					this.SendPropertyChanged("ClubName");
					this.OnClubNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePosted", DbType="Date")]
		public System.Nullable<System.DateTime> DatePosted
		{
			get
			{
				return this._DatePosted;
			}
			set
			{
				if ((this._DatePosted != value))
				{
					this.OnDatePostedChanging(value);
					this.SendPropertyChanging();
					this._DatePosted = value;
					this.SendPropertyChanged("DatePosted");
					this.OnDatePostedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(MAX)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(MAX)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRemove", DbType="Date")]
		public System.Nullable<System.DateTime> DateRemove
		{
			get
			{
				return this._DateRemove;
			}
			set
			{
				if ((this._DateRemove != value))
				{
					this.OnDateRemoveChanging(value);
					this.SendPropertyChanging();
					this._DateRemove = value;
					this.SendPropertyChanged("DateRemove");
					this.OnDateRemoveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this.OnRegionIDChanging(value);
					this.SendPropertyChanging();
					this._RegionID = value;
					this.SendPropertyChanged("RegionID");
					this.OnRegionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoachesCornerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CoachesCornerID
		{
			get
			{
				return this._CoachesCornerID;
			}
			set
			{
				if ((this._CoachesCornerID != value))
				{
					this.OnCoachesCornerIDChanging(value);
					this.SendPropertyChanging();
					this._CoachesCornerID = value;
					this.SendPropertyChanged("CoachesCornerID");
					this.OnCoachesCornerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Region")]
	public partial class Region : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegionID;
		
		private string _Region1;
		
		private int _CountryID;
		
		private string _Images;
		
		private EntityRef<Country> _Country;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegionIDChanging(int value);
    partial void OnRegionIDChanged();
    partial void OnRegion1Changing(string value);
    partial void OnRegion1Changed();
    partial void OnCountryIDChanging(int value);
    partial void OnCountryIDChanged();
    partial void OnImagesChanging(string value);
    partial void OnImagesChanged();
    #endregion
		
		public Region()
		{
			this._Country = default(EntityRef<Country>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this.OnRegionIDChanging(value);
					this.SendPropertyChanging();
					this._RegionID = value;
					this.SendPropertyChanged("RegionID");
					this.OnRegionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Region", Storage="_Region1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Region1
		{
			get
			{
				return this._Region1;
			}
			set
			{
				if ((this._Region1 != value))
				{
					this.OnRegion1Changing(value);
					this.SendPropertyChanging();
					this._Region1 = value;
					this.SendPropertyChanged("Region1");
					this.OnRegion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="Int NOT NULL")]
		public int CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					if (this._Country.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCountryIDChanging(value);
					this.SendPropertyChanging();
					this._CountryID = value;
					this.SendPropertyChanged("CountryID");
					this.OnCountryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Country_Region", Storage="_Country", ThisKey="CountryID", OtherKey="CountryID", IsForeignKey=true)]
		public Country Country
		{
			get
			{
				return this._Country.Entity;
			}
			set
			{
				Country previousValue = this._Country.Entity;
				if (((previousValue != value) 
							|| (this._Country.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Country.Entity = null;
						previousValue.Regions.Remove(this);
					}
					this._Country.Entity = value;
					if ((value != null))
					{
						value.Regions.Add(this);
						this._CountryID = value.CountryID;
					}
					else
					{
						this._CountryID = default(int);
					}
					this.SendPropertyChanged("Country");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tournament")]
	public partial class Tournament : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TournamentID;
		
		private string _name;
		
		private string _location;
		
		private System.Nullable<System.DateTime> _eventDate;
		
		private string _eventTime;
		
		private string _hostingClubName;
		
		private string _ageGroup;
		
		private string _leagueApproval;
		
		private System.Nullable<decimal> _teamFee;
		
		private System.Nullable<System.DateTime> _registrationDeadline;
		
		private string _contactName;
		
		private string _contactNumber;
		
		private string _contactEmail;
		
		private string _paidListing;
		
		private System.Nullable<System.DateTime> _membershipExpires;
		
		private string _description;
		
		private string _gender;
		
		private string _hostingClubSite;
		
		private string _format;
		
		private System.Nullable<int> _regionID;
		
		private string _imageURL;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTournamentIDChanging(int value);
    partial void OnTournamentIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OneventDateChanging(System.Nullable<System.DateTime> value);
    partial void OneventDateChanged();
    partial void OneventTimeChanging(string value);
    partial void OneventTimeChanged();
    partial void OnhostingClubNameChanging(string value);
    partial void OnhostingClubNameChanged();
    partial void OnageGroupChanging(string value);
    partial void OnageGroupChanged();
    partial void OnleagueApprovalChanging(string value);
    partial void OnleagueApprovalChanged();
    partial void OnteamFeeChanging(System.Nullable<decimal> value);
    partial void OnteamFeeChanged();
    partial void OnregistrationDeadlineChanging(System.Nullable<System.DateTime> value);
    partial void OnregistrationDeadlineChanged();
    partial void OncontactNameChanging(string value);
    partial void OncontactNameChanged();
    partial void OncontactNumberChanging(string value);
    partial void OncontactNumberChanged();
    partial void OncontactEmailChanging(string value);
    partial void OncontactEmailChanged();
    partial void OnpaidListingChanging(string value);
    partial void OnpaidListingChanged();
    partial void OnmembershipExpiresChanging(System.Nullable<System.DateTime> value);
    partial void OnmembershipExpiresChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnhostingClubSiteChanging(string value);
    partial void OnhostingClubSiteChanged();
    partial void OnformatChanging(string value);
    partial void OnformatChanged();
    partial void OnregionIDChanging(System.Nullable<int> value);
    partial void OnregionIDChanged();
    partial void OnimageURLChanging(string value);
    partial void OnimageURLChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public Tournament()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TournamentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TournamentID
		{
			get
			{
				return this._TournamentID;
			}
			set
			{
				if ((this._TournamentID != value))
				{
					this.OnTournamentIDChanging(value);
					this.SendPropertyChanging();
					this._TournamentID = value;
					this.SendPropertyChanged("TournamentID");
					this.OnTournamentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventDate", DbType="Date")]
		public System.Nullable<System.DateTime> eventDate
		{
			get
			{
				return this._eventDate;
			}
			set
			{
				if ((this._eventDate != value))
				{
					this.OneventDateChanging(value);
					this.SendPropertyChanging();
					this._eventDate = value;
					this.SendPropertyChanged("eventDate");
					this.OneventDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventTime", DbType="VarChar(50)")]
		public string eventTime
		{
			get
			{
				return this._eventTime;
			}
			set
			{
				if ((this._eventTime != value))
				{
					this.OneventTimeChanging(value);
					this.SendPropertyChanging();
					this._eventTime = value;
					this.SendPropertyChanged("eventTime");
					this.OneventTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubName", DbType="VarChar(50)")]
		public string hostingClubName
		{
			get
			{
				return this._hostingClubName;
			}
			set
			{
				if ((this._hostingClubName != value))
				{
					this.OnhostingClubNameChanging(value);
					this.SendPropertyChanging();
					this._hostingClubName = value;
					this.SendPropertyChanged("hostingClubName");
					this.OnhostingClubNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ageGroup", DbType="VarChar(50)")]
		public string ageGroup
		{
			get
			{
				return this._ageGroup;
			}
			set
			{
				if ((this._ageGroup != value))
				{
					this.OnageGroupChanging(value);
					this.SendPropertyChanging();
					this._ageGroup = value;
					this.SendPropertyChanged("ageGroup");
					this.OnageGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leagueApproval", DbType="VarChar(50)")]
		public string leagueApproval
		{
			get
			{
				return this._leagueApproval;
			}
			set
			{
				if ((this._leagueApproval != value))
				{
					this.OnleagueApprovalChanging(value);
					this.SendPropertyChanging();
					this._leagueApproval = value;
					this.SendPropertyChanged("leagueApproval");
					this.OnleagueApprovalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamFee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> teamFee
		{
			get
			{
				return this._teamFee;
			}
			set
			{
				if ((this._teamFee != value))
				{
					this.OnteamFeeChanging(value);
					this.SendPropertyChanging();
					this._teamFee = value;
					this.SendPropertyChanged("teamFee");
					this.OnteamFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationDeadline", DbType="Date")]
		public System.Nullable<System.DateTime> registrationDeadline
		{
			get
			{
				return this._registrationDeadline;
			}
			set
			{
				if ((this._registrationDeadline != value))
				{
					this.OnregistrationDeadlineChanging(value);
					this.SendPropertyChanging();
					this._registrationDeadline = value;
					this.SendPropertyChanged("registrationDeadline");
					this.OnregistrationDeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactName", DbType="VarChar(50)")]
		public string contactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				if ((this._contactName != value))
				{
					this.OncontactNameChanging(value);
					this.SendPropertyChanging();
					this._contactName = value;
					this.SendPropertyChanged("contactName");
					this.OncontactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="VarChar(25)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this.OncontactNumberChanging(value);
					this.SendPropertyChanging();
					this._contactNumber = value;
					this.SendPropertyChanged("contactNumber");
					this.OncontactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactEmail", DbType="VarChar(50)")]
		public string contactEmail
		{
			get
			{
				return this._contactEmail;
			}
			set
			{
				if ((this._contactEmail != value))
				{
					this.OncontactEmailChanging(value);
					this.SendPropertyChanging();
					this._contactEmail = value;
					this.SendPropertyChanged("contactEmail");
					this.OncontactEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paidListing", DbType="VarChar(50)")]
		public string paidListing
		{
			get
			{
				return this._paidListing;
			}
			set
			{
				if ((this._paidListing != value))
				{
					this.OnpaidListingChanging(value);
					this.SendPropertyChanging();
					this._paidListing = value;
					this.SendPropertyChanged("paidListing");
					this.OnpaidListingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membershipExpires", DbType="Date")]
		public System.Nullable<System.DateTime> membershipExpires
		{
			get
			{
				return this._membershipExpires;
			}
			set
			{
				if ((this._membershipExpires != value))
				{
					this.OnmembershipExpiresChanging(value);
					this.SendPropertyChanging();
					this._membershipExpires = value;
					this.SendPropertyChanged("membershipExpires");
					this.OnmembershipExpiresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubSite", DbType="VarChar(50)")]
		public string hostingClubSite
		{
			get
			{
				return this._hostingClubSite;
			}
			set
			{
				if ((this._hostingClubSite != value))
				{
					this.OnhostingClubSiteChanging(value);
					this.SendPropertyChanging();
					this._hostingClubSite = value;
					this.SendPropertyChanged("hostingClubSite");
					this.OnhostingClubSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format", DbType="VarChar(50)")]
		public string format
		{
			get
			{
				return this._format;
			}
			set
			{
				if ((this._format != value))
				{
					this.OnformatChanging(value);
					this.SendPropertyChanging();
					this._format = value;
					this.SendPropertyChanged("format");
					this.OnformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionID", DbType="Int")]
		public System.Nullable<int> regionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				if ((this._regionID != value))
				{
					this.OnregionIDChanging(value);
					this.SendPropertyChanging();
					this._regionID = value;
					this.SendPropertyChanged("regionID");
					this.OnregionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageURL", DbType="VarChar(MAX)")]
		public string imageURL
		{
			get
			{
				return this._imageURL;
			}
			set
			{
				if ((this._imageURL != value))
				{
					this.OnimageURLChanging(value);
					this.SendPropertyChanging();
					this._imageURL = value;
					this.SendPropertyChanged("imageURL");
					this.OnimageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _aspnet_User;
		
		private int _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaspnet_UserChanging(string value);
    partial void Onaspnet_UserChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_User", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string aspnet_User
		{
			get
			{
				return this._aspnet_User;
			}
			set
			{
				if ((this._aspnet_User != value))
				{
					this.Onaspnet_UserChanging(value);
					this.SendPropertyChanging();
					this._aspnet_User = value;
					this.SendPropertyChanged("aspnet_User");
					this.Onaspnet_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Country")]
	public partial class Country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Country1;
		
		private int _CountryID;
		
		private EntitySet<Region> _Regions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountry1Changing(string value);
    partial void OnCountry1Changed();
    partial void OnCountryIDChanging(int value);
    partial void OnCountryIDChanged();
    #endregion
		
		public Country()
		{
			this._Regions = new EntitySet<Region>(new Action<Region>(this.attach_Regions), new Action<Region>(this.detach_Regions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Country", Storage="_Country1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Country1
		{
			get
			{
				return this._Country1;
			}
			set
			{
				if ((this._Country1 != value))
				{
					this.OnCountry1Changing(value);
					this.SendPropertyChanging();
					this._Country1 = value;
					this.SendPropertyChanged("Country1");
					this.OnCountry1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					this.OnCountryIDChanging(value);
					this.SendPropertyChanging();
					this._CountryID = value;
					this.SendPropertyChanged("CountryID");
					this.OnCountryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Country_Region", Storage="_Regions", ThisKey="CountryID", OtherKey="CountryID")]
		public EntitySet<Region> Regions
		{
			get
			{
				return this._Regions;
			}
			set
			{
				this._Regions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Regions(Region entity)
		{
			this.SendPropertyChanging();
			entity.Country = this;
		}
		
		private void detach_Regions(Region entity)
		{
			this.SendPropertyChanging();
			entity.Country = null;
		}
	}
	
	public partial class GetAllActiveCoachesCornerListingsResult
	{
		
		private string _AgeGroup;
		
		private string _Gender;
		
		private string _TeamName;
		
		private string _ClubName;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DatePosted;
		
		private string _ContactName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _Website;
		
		private System.Nullable<System.DateTime> _DateRemove;
		
		private string _City;
		
		private System.Nullable<int> _RegionID;
		
		private int _CoachesCornerID;
		
		private System.Nullable<int> _UserID;
		
		public GetAllActiveCoachesCornerListingsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(MAX)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this._AgeGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="VarChar(MAX)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this._TeamName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="VarChar(MAX)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this._ClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePosted", DbType="Date")]
		public System.Nullable<System.DateTime> DatePosted
		{
			get
			{
				return this._DatePosted;
			}
			set
			{
				if ((this._DatePosted != value))
				{
					this._DatePosted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(MAX)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(MAX)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRemove", DbType="Date")]
		public System.Nullable<System.DateTime> DateRemove
		{
			get
			{
				return this._DateRemove;
			}
			set
			{
				if ((this._DateRemove != value))
				{
					this._DateRemove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoachesCornerID", DbType="Int NOT NULL")]
		public int CoachesCornerID
		{
			get
			{
				return this._CoachesCornerID;
			}
			set
			{
				if ((this._CoachesCornerID != value))
				{
					this._CoachesCornerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class GetCoachesCornerRegionListingResult
	{
		
		private string _AgeGroup;
		
		private string _Gender;
		
		private string _TeamName;
		
		private string _ClubName;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DatePosted;
		
		private string _ContactName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _Website;
		
		private System.Nullable<System.DateTime> _DateRemove;
		
		private string _City;
		
		private System.Nullable<int> _RegionID;
		
		private int _CoachesCornerID;
		
		private System.Nullable<int> _UserID;
		
		public GetCoachesCornerRegionListingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(MAX)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this._AgeGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="VarChar(MAX)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this._TeamName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="VarChar(MAX)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this._ClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePosted", DbType="Date")]
		public System.Nullable<System.DateTime> DatePosted
		{
			get
			{
				return this._DatePosted;
			}
			set
			{
				if ((this._DatePosted != value))
				{
					this._DatePosted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(MAX)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(MAX)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRemove", DbType="Date")]
		public System.Nullable<System.DateTime> DateRemove
		{
			get
			{
				return this._DateRemove;
			}
			set
			{
				if ((this._DateRemove != value))
				{
					this._DateRemove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoachesCornerID", DbType="Int NOT NULL")]
		public int CoachesCornerID
		{
			get
			{
				return this._CoachesCornerID;
			}
			set
			{
				if ((this._CoachesCornerID != value))
				{
					this._CoachesCornerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class GetAllActiveTournamentsResult
	{
		
		private int _TournamentID;
		
		private string _name;
		
		private string _location;
		
		private System.Nullable<System.DateTime> _eventDate;
		
		private string _eventTime;
		
		private string _hostingClubName;
		
		private string _ageGroup;
		
		private string _leagueApproval;
		
		private System.Nullable<decimal> _teamFee;
		
		private System.Nullable<System.DateTime> _registrationDeadline;
		
		private string _contactName;
		
		private string _contactNumber;
		
		private string _contactEmail;
		
		private string _paidListing;
		
		private System.Nullable<System.DateTime> _membershipExpires;
		
		private string _description;
		
		private string _gender;
		
		private string _hostingClubSite;
		
		private string _format;
		
		private System.Nullable<int> _regionID;
		
		private string _imageURL;
		
		private System.Nullable<int> _UserID;
		
		public GetAllActiveTournamentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TournamentID", DbType="Int NOT NULL")]
		public int TournamentID
		{
			get
			{
				return this._TournamentID;
			}
			set
			{
				if ((this._TournamentID != value))
				{
					this._TournamentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventDate", DbType="Date")]
		public System.Nullable<System.DateTime> eventDate
		{
			get
			{
				return this._eventDate;
			}
			set
			{
				if ((this._eventDate != value))
				{
					this._eventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventTime", DbType="VarChar(50)")]
		public string eventTime
		{
			get
			{
				return this._eventTime;
			}
			set
			{
				if ((this._eventTime != value))
				{
					this._eventTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubName", DbType="VarChar(50)")]
		public string hostingClubName
		{
			get
			{
				return this._hostingClubName;
			}
			set
			{
				if ((this._hostingClubName != value))
				{
					this._hostingClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ageGroup", DbType="VarChar(50)")]
		public string ageGroup
		{
			get
			{
				return this._ageGroup;
			}
			set
			{
				if ((this._ageGroup != value))
				{
					this._ageGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leagueApproval", DbType="VarChar(50)")]
		public string leagueApproval
		{
			get
			{
				return this._leagueApproval;
			}
			set
			{
				if ((this._leagueApproval != value))
				{
					this._leagueApproval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamFee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> teamFee
		{
			get
			{
				return this._teamFee;
			}
			set
			{
				if ((this._teamFee != value))
				{
					this._teamFee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationDeadline", DbType="Date")]
		public System.Nullable<System.DateTime> registrationDeadline
		{
			get
			{
				return this._registrationDeadline;
			}
			set
			{
				if ((this._registrationDeadline != value))
				{
					this._registrationDeadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactName", DbType="VarChar(50)")]
		public string contactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				if ((this._contactName != value))
				{
					this._contactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="VarChar(25)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this._contactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactEmail", DbType="VarChar(50)")]
		public string contactEmail
		{
			get
			{
				return this._contactEmail;
			}
			set
			{
				if ((this._contactEmail != value))
				{
					this._contactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paidListing", DbType="VarChar(50)")]
		public string paidListing
		{
			get
			{
				return this._paidListing;
			}
			set
			{
				if ((this._paidListing != value))
				{
					this._paidListing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membershipExpires", DbType="Date")]
		public System.Nullable<System.DateTime> membershipExpires
		{
			get
			{
				return this._membershipExpires;
			}
			set
			{
				if ((this._membershipExpires != value))
				{
					this._membershipExpires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubSite", DbType="VarChar(50)")]
		public string hostingClubSite
		{
			get
			{
				return this._hostingClubSite;
			}
			set
			{
				if ((this._hostingClubSite != value))
				{
					this._hostingClubSite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format", DbType="VarChar(50)")]
		public string format
		{
			get
			{
				return this._format;
			}
			set
			{
				if ((this._format != value))
				{
					this._format = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionID", DbType="Int")]
		public System.Nullable<int> regionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				if ((this._regionID != value))
				{
					this._regionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageURL", DbType="VarChar(MAX)")]
		public string imageURL
		{
			get
			{
				return this._imageURL;
			}
			set
			{
				if ((this._imageURL != value))
				{
					this._imageURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class GetAllCoachesCornerListingsResult
	{
		
		private string _AgeGroup;
		
		private string _Gender;
		
		private string _TeamName;
		
		private string _ClubName;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DatePosted;
		
		private string _ContactName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _Website;
		
		private System.Nullable<System.DateTime> _DateRemove;
		
		private string _City;
		
		private System.Nullable<int> _RegionID;
		
		private int _CoachesCornerID;
		
		private System.Nullable<int> _UserID;
		
		public GetAllCoachesCornerListingsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(MAX)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this._AgeGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="VarChar(MAX)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this._TeamName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="VarChar(MAX)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this._ClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePosted", DbType="Date")]
		public System.Nullable<System.DateTime> DatePosted
		{
			get
			{
				return this._DatePosted;
			}
			set
			{
				if ((this._DatePosted != value))
				{
					this._DatePosted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(MAX)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(MAX)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRemove", DbType="Date")]
		public System.Nullable<System.DateTime> DateRemove
		{
			get
			{
				return this._DateRemove;
			}
			set
			{
				if ((this._DateRemove != value))
				{
					this._DateRemove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoachesCornerID", DbType="Int NOT NULL")]
		public int CoachesCornerID
		{
			get
			{
				return this._CoachesCornerID;
			}
			set
			{
				if ((this._CoachesCornerID != value))
				{
					this._CoachesCornerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class GetAllTournamentsResult
	{
		
		private int _TournamentID;
		
		private string _name;
		
		private string _location;
		
		private System.Nullable<System.DateTime> _eventDate;
		
		private string _eventTime;
		
		private string _hostingClubName;
		
		private string _ageGroup;
		
		private string _leagueApproval;
		
		private System.Nullable<decimal> _teamFee;
		
		private System.Nullable<System.DateTime> _registrationDeadline;
		
		private string _contactName;
		
		private string _contactNumber;
		
		private string _contactEmail;
		
		private string _paidListing;
		
		private System.Nullable<System.DateTime> _membershipExpires;
		
		private string _description;
		
		private string _gender;
		
		private string _hostingClubSite;
		
		private string _format;
		
		private System.Nullable<int> _regionID;
		
		private string _imageURL;
		
		private System.Nullable<int> _UserID;
		
		public GetAllTournamentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TournamentID", DbType="Int NOT NULL")]
		public int TournamentID
		{
			get
			{
				return this._TournamentID;
			}
			set
			{
				if ((this._TournamentID != value))
				{
					this._TournamentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventDate", DbType="Date")]
		public System.Nullable<System.DateTime> eventDate
		{
			get
			{
				return this._eventDate;
			}
			set
			{
				if ((this._eventDate != value))
				{
					this._eventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventTime", DbType="VarChar(50)")]
		public string eventTime
		{
			get
			{
				return this._eventTime;
			}
			set
			{
				if ((this._eventTime != value))
				{
					this._eventTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubName", DbType="VarChar(50)")]
		public string hostingClubName
		{
			get
			{
				return this._hostingClubName;
			}
			set
			{
				if ((this._hostingClubName != value))
				{
					this._hostingClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ageGroup", DbType="VarChar(50)")]
		public string ageGroup
		{
			get
			{
				return this._ageGroup;
			}
			set
			{
				if ((this._ageGroup != value))
				{
					this._ageGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leagueApproval", DbType="VarChar(50)")]
		public string leagueApproval
		{
			get
			{
				return this._leagueApproval;
			}
			set
			{
				if ((this._leagueApproval != value))
				{
					this._leagueApproval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamFee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> teamFee
		{
			get
			{
				return this._teamFee;
			}
			set
			{
				if ((this._teamFee != value))
				{
					this._teamFee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationDeadline", DbType="Date")]
		public System.Nullable<System.DateTime> registrationDeadline
		{
			get
			{
				return this._registrationDeadline;
			}
			set
			{
				if ((this._registrationDeadline != value))
				{
					this._registrationDeadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactName", DbType="VarChar(50)")]
		public string contactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				if ((this._contactName != value))
				{
					this._contactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="VarChar(25)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this._contactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactEmail", DbType="VarChar(50)")]
		public string contactEmail
		{
			get
			{
				return this._contactEmail;
			}
			set
			{
				if ((this._contactEmail != value))
				{
					this._contactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paidListing", DbType="VarChar(50)")]
		public string paidListing
		{
			get
			{
				return this._paidListing;
			}
			set
			{
				if ((this._paidListing != value))
				{
					this._paidListing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membershipExpires", DbType="Date")]
		public System.Nullable<System.DateTime> membershipExpires
		{
			get
			{
				return this._membershipExpires;
			}
			set
			{
				if ((this._membershipExpires != value))
				{
					this._membershipExpires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubSite", DbType="VarChar(50)")]
		public string hostingClubSite
		{
			get
			{
				return this._hostingClubSite;
			}
			set
			{
				if ((this._hostingClubSite != value))
				{
					this._hostingClubSite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format", DbType="VarChar(50)")]
		public string format
		{
			get
			{
				return this._format;
			}
			set
			{
				if ((this._format != value))
				{
					this._format = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionID", DbType="Int")]
		public System.Nullable<int> regionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				if ((this._regionID != value))
				{
					this._regionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageURL", DbType="VarChar(MAX)")]
		public string imageURL
		{
			get
			{
				return this._imageURL;
			}
			set
			{
				if ((this._imageURL != value))
				{
					this._imageURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class GetAllTournamentsByUserResult
	{
		
		private int _TournamentID;
		
		private string _name;
		
		private string _location;
		
		private System.Nullable<System.DateTime> _eventDate;
		
		private string _eventTime;
		
		private string _hostingClubName;
		
		private string _ageGroup;
		
		private string _leagueApproval;
		
		private System.Nullable<decimal> _teamFee;
		
		private System.Nullable<System.DateTime> _registrationDeadline;
		
		private string _contactName;
		
		private string _contactNumber;
		
		private string _contactEmail;
		
		private string _paidListing;
		
		private System.Nullable<System.DateTime> _membershipExpires;
		
		private string _description;
		
		private string _gender;
		
		private string _hostingClubSite;
		
		private string _format;
		
		private System.Nullable<int> _regionID;
		
		private string _imageURL;
		
		private System.Nullable<int> _UserID;
		
		public GetAllTournamentsByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TournamentID", DbType="Int NOT NULL")]
		public int TournamentID
		{
			get
			{
				return this._TournamentID;
			}
			set
			{
				if ((this._TournamentID != value))
				{
					this._TournamentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventDate", DbType="Date")]
		public System.Nullable<System.DateTime> eventDate
		{
			get
			{
				return this._eventDate;
			}
			set
			{
				if ((this._eventDate != value))
				{
					this._eventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventTime", DbType="VarChar(50)")]
		public string eventTime
		{
			get
			{
				return this._eventTime;
			}
			set
			{
				if ((this._eventTime != value))
				{
					this._eventTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubName", DbType="VarChar(50)")]
		public string hostingClubName
		{
			get
			{
				return this._hostingClubName;
			}
			set
			{
				if ((this._hostingClubName != value))
				{
					this._hostingClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ageGroup", DbType="VarChar(50)")]
		public string ageGroup
		{
			get
			{
				return this._ageGroup;
			}
			set
			{
				if ((this._ageGroup != value))
				{
					this._ageGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leagueApproval", DbType="VarChar(50)")]
		public string leagueApproval
		{
			get
			{
				return this._leagueApproval;
			}
			set
			{
				if ((this._leagueApproval != value))
				{
					this._leagueApproval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamFee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> teamFee
		{
			get
			{
				return this._teamFee;
			}
			set
			{
				if ((this._teamFee != value))
				{
					this._teamFee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationDeadline", DbType="Date")]
		public System.Nullable<System.DateTime> registrationDeadline
		{
			get
			{
				return this._registrationDeadline;
			}
			set
			{
				if ((this._registrationDeadline != value))
				{
					this._registrationDeadline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactName", DbType="VarChar(50)")]
		public string contactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				if ((this._contactName != value))
				{
					this._contactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="VarChar(25)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this._contactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactEmail", DbType="VarChar(50)")]
		public string contactEmail
		{
			get
			{
				return this._contactEmail;
			}
			set
			{
				if ((this._contactEmail != value))
				{
					this._contactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paidListing", DbType="VarChar(50)")]
		public string paidListing
		{
			get
			{
				return this._paidListing;
			}
			set
			{
				if ((this._paidListing != value))
				{
					this._paidListing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membershipExpires", DbType="Date")]
		public System.Nullable<System.DateTime> membershipExpires
		{
			get
			{
				return this._membershipExpires;
			}
			set
			{
				if ((this._membershipExpires != value))
				{
					this._membershipExpires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostingClubSite", DbType="VarChar(50)")]
		public string hostingClubSite
		{
			get
			{
				return this._hostingClubSite;
			}
			set
			{
				if ((this._hostingClubSite != value))
				{
					this._hostingClubSite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format", DbType="VarChar(50)")]
		public string format
		{
			get
			{
				return this._format;
			}
			set
			{
				if ((this._format != value))
				{
					this._format = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionID", DbType="Int")]
		public System.Nullable<int> regionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				if ((this._regionID != value))
				{
					this._regionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageURL", DbType="VarChar(MAX)")]
		public string imageURL
		{
			get
			{
				return this._imageURL;
			}
			set
			{
				if ((this._imageURL != value))
				{
					this._imageURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class GetCoachesCornerRegionListingByAgeResult
	{
		
		private string _AgeGroup;
		
		private string _Gender;
		
		private string _TeamName;
		
		private string _ClubName;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DatePosted;
		
		private string _ContactName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _Website;
		
		private System.Nullable<System.DateTime> _DateRemove;
		
		private string _City;
		
		private System.Nullable<int> _RegionID;
		
		private int _CoachesCornerID;
		
		private System.Nullable<int> _UserID;
		
		public GetCoachesCornerRegionListingByAgeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(MAX)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this._AgeGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="VarChar(MAX)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this._TeamName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="VarChar(MAX)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this._ClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePosted", DbType="Date")]
		public System.Nullable<System.DateTime> DatePosted
		{
			get
			{
				return this._DatePosted;
			}
			set
			{
				if ((this._DatePosted != value))
				{
					this._DatePosted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(MAX)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(MAX)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRemove", DbType="Date")]
		public System.Nullable<System.DateTime> DateRemove
		{
			get
			{
				return this._DateRemove;
			}
			set
			{
				if ((this._DateRemove != value))
				{
					this._DateRemove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoachesCornerID", DbType="Int NOT NULL")]
		public int CoachesCornerID
		{
			get
			{
				return this._CoachesCornerID;
			}
			set
			{
				if ((this._CoachesCornerID != value))
				{
					this._CoachesCornerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
